### ISSUE TITLE
It works with this server 

### ISSUE THREAD

**Issue by Vasilis553** [intNeo/gt_client_2024#3]
Hello Tha client works with this server:
https://github.com/4malgama/gtanks_server_remake

**Comment by intNeo** [comment]
Hello! This client is designed for the "merged" build of the tanks server (January-February 2018).
If your server accepts the "old" client authorization keys, and has an "old" database structure, then it may work.

**Comment by intNeo** [comment]
Hello! This client is designed for a "self-written" gtanks server build (January 2024).
There are significant changes in this server and the "authorization" keys have been completely redesigned.

**Comment by Vasilis553** [comment]
It means that we cannot use this client on this server
Do you Hava the server?

**Comment by intNeo** [comment]
Hello! Yes, there is a server, even partially modifiable in the Intellij IDEA environment (openjdk-21 is used).
I can sell it for RUB 1500. ~$ 16,05

**Comment by Vasilis553** [comment]
Do you have any video or something to see how is the server and user interface?

**Comment by intNeo** [comment]
https://www.youtube.com/watch?v=0ts5thKDH6o

**Comment by intNeo** [comment]
![win_sandbox-2024-04-21-19-27-20](https://github.com/intNeo/gt_client_2024/assets/142940431/8ee8faf8-d402-4950-82d9-0a55e5b79fde)
![43886 Картинка 523x333](https://github.com/intNeo/gt_client_2024/assets/142940431/0e503e51-b399-4eb2-b153-d5cdff3f3caf)
![win_sandbox-2024-04-21-19-20-41](https://github.com/intNeo/gt_client_2024/assets/142940431/ae50137b-f1c8-4ebf-ae2b-2b02bc23fe12)
![win_sandbox-2024-04-21-19-20-52](https://github.com/intNeo/gt_client_2024/assets/142940431/94e44e46-fe3f-47ab-a2cc-72eff9e98627)
![win_sandbox-2024-04-21-19-25-21](https://github.com/intNeo/gt_client_2024/assets/142940431/dfdb5cd1-6d3b-4339-8c10-f963bf174ac2)

**Comment by intNeo** [comment]
Here are more screenshots to confirm. How do you like the deal?

**Comment by Vasilis553** [comment]
> Here are more screenshots to confirm. How do you like the deal?

I will talk with my other guy and I will inform I would like a discord name and what payment methods you use and our currency is euro

**Comment by intNeo** [comment]
My nickname in discord: int_neo
There may be a problem with payment, since you understand the situation in the world yourself.
Therefore, the only option for me is Donation Alerts.
Here: https://www.donationalerts.com/r/intneo
Specify the nickname then, the amount is then in euros 15.06 and the comments "GTANKS 2024". After that, I will send you a link.
